### ISSUE TITLE
MSBuildLocator doesn't work with multiple level SDK resolution logic for NET 6 SDK.

### ISSUE THREAD

**Issue by lifengl** [microsoft/MSBuildLocator#274]
Repro

1, Install NET 7/8 SDK to the machine level
2, Download zip of NET 6 SDK, unzip to a private folder
3, set dotnet path of NET 6 SDK to the front of PATH environment
4, use dotnet --info all SDKs/Runtimes will be listed
5, use MSBuildLocator in this case, it would not resolve NET 7/8 SDKs

Note:
1. this can be controlled by "DOTNET_MULTILEVEL_LOOKUP" environment variable
2. this behavior is removed from NET 7 and beyond, so this is narrow to the problem when the local installation is older than NET 7.

**Comment by YuliiaKovalova** [comment]
Hi @lifengl,

We have discussed and agreed to push back on this one, since [hostfxr api ](https://github.com/dotnet/runtime/blob/2106224d35cc81e04234bc4d4daaf8f944fceeca/src/native/corehost/fxr/hostfxr.cpp#L417) doesn't provide a way to request MLL and we are moving towards the end of net6 support. 
cc: @baronfel
