### ISSUE TITLE
Could not load type 'Microsoft.Build.Execution.BuildResultBase'

### ISSUE THREAD

**Issue by ChezMose** [microsoft/MSBuildLocator#315]
I used MSBuildLocator for months in a Winform project and it worked perfectly.
After a recent update of Visual Studio 2022 and NuGet packages in that project, I had a new error when building that project using MSBuildLocator, telling me to avoid copying MSBuild to output, using <ExcludeAssets>. Which I did.

Problem is... since that change I have an exception after the build when I want to read the build result:
`System.TypeLoadException : Could not load type 'Microsoft.Build.Execution.BuildResultBase' from assembly 'Microsoft.Build, Version=15.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'`

    var buildResult = BuildManager.DefaultBuildManager.Build(parameters, request);

    try
    {
        // THIS IS WHERE THE EXCEPTION OCCURS
        status = this.HandleBuildResult(buildResult);
        if (!status.IsSuccess)
            return status;
    }
    catch (Exception exc)
    {
        ...
    }

A few info:
- It'a winform project
- MSBuildLocator.RegisterDefaults() is called in the constructor of the class what performs the build. I tried putting it at the beginning of the Main() but it did not make a difference.
- the build is performed, but I have to way to know if it worked, apart from reading the logs, which is meh.

Here are the references:

    <PackageReference Include="Microsoft.Build">
        <Version>17.12.6</Version>
        <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Build.Framework">
        <Version>17.12.6</Version>
        <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Build.Locator">
        <Version>1.7.8</Version>
    </PackageReference>

How can I know that the build succeeded with a better way than reading the logs ?

**Comment by YuliiaKovalova** [comment]
Hi @ChezMose ,

When you use `BuildManager.DefaultBuildManager`, it's a static instance that might have been initialized _before_ MSBuildLocator was registered.
This can cause it to load the wrong version of MSBuild assemblies from the GAC or other locations, instead of using the version MSBuildLocator discovered.

Please try to modify your code like this:

```
// 1. Register MSBuildLocator first, before any MSBuild types are accessed
MSBuildLocator.RegisterDefaults();

// 2. Create a new instance instead of using the static DefaultBuildManager
using (var buildManager = new BuildManager())
{
    var buildResult = buildManager.Build(parameters, request);
    try
    {
        status = this.HandleBuildResult(buildResult);
        if (!status.IsSuccess)
            return status;
    }
    catch (Exception exc)
    {
        // ...
    }
}

```

**Comment by ChezMose** [comment]
Hi @YuliiaKovalova,
Thanks for your answer, unfortunately that did not do the trick: I still have the same exception at the same line.
Too bad, I liked the fix and the explanation !

**Comment by YuliiaKovalova** [comment]
Hi @ChezMose,
Could you please share a fusion log trace of an attempted build? You can do it with [fuslogvw.exe](https://docs.microsoft.com/dotnet/framework/tools/fuslogvw-exe-assembly-binding-log-viewer), though lately I've been using [Fusion](https://github.com/awaescher/Fusion) which has a nicer UI. That should hopefully have some more information about exactly what is going wrong.

**Comment by ChezMose** [comment]
Here it is
[2024.11.07.16.52.04.6797.zip](https://github.com/user-attachments/files/17666870/2024.11.07.16.52.04.6797.zip)

Just to be accurate: the build is successful.
It's just that I cannot read the buildResult to know that programmatically.

**Comment by YuliiaKovalova** [comment]
In the log I don't see the reported error, could you please collect it when you hit the issue?
To give more context: BuildResultBase was added recently, and there must be something that attempts to load the previous Microsoft.Build.dll version without it.

**Comment by ChezMose** [comment]
_"there must be something that attempts to load the previous Microsoft.Build.dll version without it."_
To give more context as well: I previously had Visual Studio 2019 and maybe an older version as well on that computer.
Thay have been installed since.

**Comment by YuliiaKovalova** [comment]
@ChezMose , thank you for these details.

Sorry, but we need more information from since, since nothing clicks from fusion logs.
Please run https://github.com/microsoft/msbuild/blob/2d82e1a861d890fce68c8e2d42b569e5bbaf5687/scripts/EnumerateMSBuild.ps1 and share the results with us. You might have a Visual Studio installation problem, or you might have MSBuild assemblies in your Global Assembly Cache (GAC). If it's the latter, the instructions from [this feedback issue](https://developercommunity.visualstudio.com/solutions/219148/view.html) might help you.

**Comment by ChezMose** [comment]
@YuliiaKovalova sorry for the delay, hereis the result or the ps script
[msbuild_versions.txt](https://github.com/user-attachments/files/17731067/msbuild_versions.txt)

btw, the link you shared to the feedback issue seems to be a dead link

**Comment by YuliiaKovalova** [comment]
@ChezMose, thank you for this log!

After looking at this log together with @rainersigwald , we managed to find a reason.
According to fusion log,  Microsoft.Build.dll is loaded from  `C:\Program Files\Microsoft Visual Studio\2022\Professional\MSBuild\Current\Bin\`, and from the second log we know that VS version in this directory is **17.11.35327.3**.

The existing limitation is that the Microsoft.Build assembly version of your project dependency should be less or equal to 17.11 due to runtime environment.
As a medicine here:
1. Update VS to 17.12
or
2. Target Microsoft.Build 17.11 or lower.

We are thinking about improving our API so we can report these issues as a part of MSBuild.Locator execution, but for now please try what is recommended above.

**Comment by ChezMose** [comment]
Thanks @YuliiaKovalova, updating VS worked like a charm.
I feel a bit unluncky to have encountered that issue just after updating VS, to have the fix released a few days later ^^

Thanks for your patience and your hard work !

**Comment by YuliiaKovalova** [comment]
@ChezMose , thank you for being a very responsive and cooperating customer!
We are always ready to help.

Happy coding! :)
